server:
  port: 8848

eureka:
  server:
    eviction-interval-timer-in-ms: 3000
  instance:
    hostname: 192.168.0.4
    #prefer-ip-address: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/