spring:
  #mysql
  datasource:
    username: root
    password: yh3trfv6I2@s1ss
#    url: jdbc:mysql://localhost:3306/spring-cloud-demo?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    url: jdbc:mysql://101.201.154.161:3306/powerdb_zjm?useSSL=false&characterEncoding=UTF-8&queryTimeout=2400&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: webPool
  #redis
  redis:
    host: 47.108.77.91
    port: 6379
    timeout: 30000
    database: 1
    password: 7426998ZcjYzh
    jedis:
      pool:
        max-active: 10 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 0 #连接池中的最小空闲连接
  #通用时间解析
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8848/eureka/


#mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.demo.cloud.user.*.entity.po
  global-config:
    #数据库相关配置
    db-config:
      id-type: ASSIGN_ID
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: delFlag
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 配置白名单路径
white-list:
  urls:
    - "/v2/api-docs/**"
    - "/inner/**"
# 线程池配置
pool:
  core-size: 9
  max-size: 30
  keep-alive-time: 100

logging:
  level:
    root: info
#    com/dcsyun/cloud/sys/mapper
    com:
      dcsyun:
        cloud:
          sys:
            mapper: debug
    org:
      mybatis: debug

#启用knife4j增强模式
knife4j:
  enable: true
  #生产模式屏蔽, true将禁止访问API在线文档, false可以看到文档, 密码失效

  production: false
  #Basic认证功能，即是否需要通过用户名、密码验证后才可以访问在线API文档
  basic:
    enable: true
    #如果开启Basic认证却未配置用户名与密码，默认是：admin/123321, 即使输入对了, 也会一直循环
    username: zhengcj
    password: 123456
  #为了节省流量, 返回数据时, 配置不返回属性值为null的数据

